### ISSUE TITLE
email contact does not work

### ISSUE THREAD

**Issue by PeterPanino** [SwiftExpat/RunTime-ToolKit#10]
When trying to contact you by email (websupport@Swiftexpat.com), the email came back with this error message: "Mail delivery failed: returning message to sender"
The following address failed: websupport@Swiftexpat.com: SMTP error from remote server for RCPT TO command, host: Swiftexpat.com (107.161.23.26) reason: 550 No Such User Here

**Comment by SwiftExpat** [comment]
The alias got dropped when I changed hosting, It works now

**Comment by SwiftExpat** [comment]
Tested with proton mail, closing issue.  Thanks for reporting
